### ISSUE TITLE
Bluetooth Controller requires repeated button pressing

### ISSUE THREAD

**Issue by Thingable** [muonide/miniCARL#1]
The miniCARL bots only move a prescribed amount of time per button press. It is more intuitive to move the bot on press and stop movement on release.

**Comment by Thingable** [comment]
I have the code in a new branch that I created, and attempted a push but I was denied access. Not sure if it is my SSH key or not being a approved developer. It's late so I will look into that tomorrow.

Also all my stuff is not tested, due to lack of bot.

**Comment by muonide** [comment]
I think taking out the delay() & stop() commands in the if( num == # & pressed) and add if( num == # ! pressed) { stop(); } statements would get the job done.  My only concern there being if it misses a packet the thing may not stop or behave wierdly.  Maybe that's worth experimenting with.

**Comment by Thingable** [comment]
I got the proposed fixed up on the issue#1 branch. I implemented an if the button was pressed check which button else if !pressed (ie released) then stop(). 

But looking at it now I think there will need to be something in the if (!pressed) that only executes stop if buttons 5-8 are released. 

*edit: the potential problem of stopping when buttons 1-4 are released should be up
